version: "3.9"
services:
    db:
        image: postgres:13-alpine
        env_file: ./.env
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        container_name: db
        ports: 
            - '5432:5432'
        volumes:
            - dbdata:/var/lib/postgresql/data/
            - ./dbscripts:/docker-entrypoint-initdb.d
        profiles: ['api-dev', 'api', 'dev']

    api-dev:
        image: nus-utils/peer-review-api:dev
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
            - JWT_SECRET=${JWT_SECRET}
            - RUN_ENV=local
            - INSERT_DUMMY=${INSERT_DUMMY}
            - ADMIN_NAME=admin
            - ADMIN_EMAIL=admin@local.com
            - ADMIN_PASSWORD=admin
        build:
            context: ./core/.
            target: builder
        volumes:
          - ./core:/app
        command: CompileDaemon --build="go build -o server" --command="./server"
        container_name: api-dev
        depends_on:
            - db
        ports:
            - '5000:5000'
        profiles: ['api-dev', 'dev']

    api-staging:
        image: nus-utils/peer-review-api:staging
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
            - JWT_SECRET=${JWT_SECRET}
            - RUN_ENV=production
            - INSERT_DUMMY=${INSERT_DUMMY}
            - ADMIN_NAME=admin
            - ADMIN_EMAIL=admin@local.com
            - ADMIN_PASSWORD=admin
        build:
            context: ./core/.
            target: builder
        volumes:
          - ./core:/app
        command: CompileDaemon --build="go build -o server" --command="./server"
        container_name: api-dev
        depends_on:
            - db
        ports:
            - '5000:5000'
        profiles: ['api-staging', 'staging']

    api:
        image: nus-utils/peer-review-api:latest
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
            - JWT_SECRET=${JWT_SECRET}
            - RUN_ENV=production
            - ADMIN_NAME=admin
            - ADMIN_EMAIL=admin@local.com
            - ADMIN_PASSWORD=admin
        build:
            context: ./core/.
        container_name: api
        depends_on:
            - db
        ports:
            - '5000:5000'
        profiles: ['api', 'prod']

    frontend-dev:
        build:
            context: ./frontend
            target: copy

        environment:
          - API_URL=http://api-dev:5000
        volumes:
          - /app/node_modules
          - ./frontend/src:/app/src
        command: npm run start
        ports:
            - '3000:3000'
        stdin_open: true
        profiles: ['dev', 'frontend-dev']

    frontend:
        build:
            context: ./frontend
        ports:
            - '3000:3000'
        stdin_open: true
        profiles: ['prod', 'frontend']

volumes:
    dbdata:
